<!DOCTYPE html [
    <!ELEMENT body (link|script|iframe)*>
    <!ELEMENT link EMPTY>
    <!ELEMENT script (#PCDATA)>
    <!ELEMENT iframe EMPTY>

    <!ATTLIST body xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml">
    <!ATTLIST script
        xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml"
        src CDATA #IMPLIED>
    <!ATTLIST link
        xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml"
        rel CDATA #IMPLIED
        href CDATA #IMPLIED>
    <!ATTLIST iframe
        xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml"
        is CDATA #FIXED "foo-bar"
        onerror CDATA #IMPLIED
        onload CDATA #IMPLIED
        src CDATA #IMPLIED>
]>
<html>
<body>
    <link rel="import" href="./bower_components/polymer/polymer.html"/>
    <script src="./bower_components/webcomponentsjs/webcomponents.js"></script>
    <script src="debug.js"></script>
<script>
  window.run = function() {
    var FooBar = Polymer({
      is: 'foo-bar',

      extends: 'iframe',

      created: function() {
        console.log("busted", this);
        debugger;
      }
    });

    var el1 = document.createElement('iframe');
    console.log("el1 is iframe", el1 instanceof HTMLIFrameElement);

    var el2 = document.createElement('iframe', 'foo-bar');
    console.log("el2 is iframe", el2 instanceof HTMLIFrameElement);
  };
</script>
</body>
</html>
